# ===============================
# URL PRODUCTION
# ===============================
app.url.backend=${BACKEND_URL}
app.url.frontend=${FRONTEND_URL}

# ===============================
# DATABASE PRODUCTION
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# SECURITY & API KEY (PRODUCTION)
# ===============================
api.jwt.base64-secret=${JWT_SECRET}
vnp.tmn-code=${VNP_TMN_CODE}
vnp.secret-key=${VNPAY_SECRET_KEY}
vnp.return-url-backend=${app.url.backend}/api/v1/payment/vnpay-return
vnp.return-url-frontend=${app.url.frontend}/user/payments/result
mapbox.api.key=${MAPBOX_API_KEY}

# ===============================
# EMAIL PRODUCTION
# ===============================
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ===============================
# GOOGLE LOGIN PRODUCTION
# ===============================
google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}