# ===============================
# URL PRODUCTION
# ===============================
app.url.backend=${BACKEND_URL}
app.url.frontend=${FRONTEND_URL}

server.port=${PORT:10000}

# Mở kết nối ra ngoài internet (BẮT BUỘC cho Render)
server.address=0.0.0.0

# ===============================
# RENDER OPTIMIZATIONS (CHỐNG TIMEOUT)
# ===============================
# Khởi động "lười" giúp giảm 30-50% thời gian boot
spring.main.lazy-initialization=true

# Tắt cảnh báo open-in-view, giúp nhẹ app hơn
spring.jpa.open-in-view=false

# Ép Hibernate không quét và update lại bảng (Giảm thời gian khởi động cực mạnh)
spring.jpa.hibernate.ddl-auto=none


# ===============================
# DATABASE PRODUCTION
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# SECURITY & API KEY (PRODUCTION)
# ===============================
api.jwt.base64-secret=${JWT_SECRET}
vnp.tmn-code=${VNP_TMN_CODE}
vnp.secret-key=${VNPAY_SECRET_KEY}
vnp.return-url-backend=${app.url.backend}/api/v1/payment/vnpay-return
vnp.return-url-frontend=${app.url.frontend}/user/payments/result
mapbox.api.key=${MAPBOX_API_KEY}

# ===============================
# EMAIL PRODUCTION
# ===============================
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ===============================
# GOOGLE LOGIN PRODUCTION
# ===============================
google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}


# ===============================
# CLOUDINARY PRODUCTION
# ===============================
app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
app.cloudinary.api-key=${CLOUDINARY_API_KEY}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET}