# ===============================
# KÍCH HOẠT PROFILE MẶC ĐỊNH
# ===============================
spring.profiles.active=local

# ===============================
# APP & SERVER (Cấu hình chung)
# ===============================
spring.application.name=bds360-backend
server.port=${PORT:10000}

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIKARI POOL (cực quan trọng)
# ===============================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#  batch insert
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true


# ===============================
# FILE UPLOAD
# ===============================
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# JWT (Cấu hình chung)
# ===============================
api.jwt.token-validity-in-seconds=86400000

# ===============================
# VNPAY (Cấu hình chung)
# ===============================
vnp.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# ===============================
# EMAIL (Cấu hình chung)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true